# Generated by Django 4.2.2 on 2023-06-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.estado')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.materia')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.tarea')),
            ],
        ),
    ]
